version: "3"

networks:
  front-tier:
  back-tier:
        
volumes:
    prometheus_data:
    grafana_data:
    targets:
    loki_data:
  

services:    
  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
      - type: bind
        source: ./scrape-targets
        target: /prometheus/targets
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - back-tier
    restart: always

  grafana:
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 5000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
      - front-tier
    restart: always
    
  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/data/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - back-tier
      
  # promtail:
  #   image: grafana/promtail:latest
  #   volumes:
  #     - /var/log:/var/log
  #     - /var/lib/docker/containers:/var/lib/docker/containers
  #     - ./promtail:/etc/promtail-config/
  #   command: -config.file=/etc/promtail-config/promtail.yml
  #   networks:
  #     - back-tier
