{
 "title": "Database",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(sync_eth2_synced{}, instance)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "\n# Database Metrics\n\nMetrics collected from a Lighthouse Beacon Node regarding the core key-value database (e.g., LevelDB).\n\nCollected from the [`store`](https://github.com/sigp/lighthouse/tree/master/beacon_node/store) crate.\n\n\n\n"
   },
   "content": "\n# Database Metrics\n\nMetrics collected from a Lighthouse Beacon Node regarding the core key-value database (e.g., LevelDB).\n\nCollected from the [`store`](https://github.com/sigp/lighthouse/tree/master/beacon_node/store) crate.\n\n\n\n"
  },
  {
   "title": "On-Disk Database Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "store_disk_db_size{instance=\"$instance\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 6 },
   "options": {
    "content": "\n### Reads per Minute\n\n\nThe global database reads per minute, expressed as operations and a cumulative bytes value.\n"
   },
   "content": "\n### Reads per Minute\n\n\nThe global database reads per minute, expressed as operations and a cumulative bytes value.\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 6 },
   "options": {
    "content": "\n### Writes per Minute\n\n\nThe global database writes per minute, expressed as operations and a cumulative bytes value.\n"
   },
   "content": "\n### Writes per Minute\n\n\nThe global database writes per minute, expressed as operations and a cumulative bytes value.\n"
  },
  {
   "title": "DB Read Operations per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Ops per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(store_disk_db_read_count_total{instance=\"$instance\"} [1m])"
    }
   ]
  },
  {
   "title": "DB Read Write (1m avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Ops per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(store_disk_db_write_count_total{instance=\"$instance\"} [1m])"
    }
   ]
  },
  {
   "title": "DB Throughput (Read) per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(store_disk_db_read_bytes_total{instance=\"$instance\"} [5m])"
    }
   ]
  },
  {
   "title": "DB Throughput (Write) (1m avg)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(store_disk_db_write_bytes_total{instance=\"$instance\"} [1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 19 },
   "options": {
    "content": "\n### Beacon state read/write overhead\n\n\nThe encoding/decoding overheads of storing `BeaconState` (excluding action bytes read/write operations).\n"
   },
   "content": "\n### Beacon state read/write overhead\n\n\nThe encoding/decoding overheads of storing `BeaconState` (excluding action bytes read/write operations).\n"
  },
  {
   "title": "Beacon State Read Overhead",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(store_beacon_state_read_overhead_seconds_sum{instance=\"$instance\"}[5m])\n/\nrate(store_beacon_state_read_overhead_seconds_count{instance=\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Beacon State Write Overhead",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(store_beacon_state_write_overhead_seconds_sum{instance=\"$instance\"}[5m])\n/\nrate(store_beacon_state_write_overhead_seconds_count{instance=\"$instance\"}[5m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "options": {
    "content": "\n### BeaconState read/writes\n\n\nNumber of `BeaconState` read/writes in operations and cumulative bytes.\n"
   },
   "content": "\n### BeaconState read/writes\n\n\nNumber of `BeaconState` read/writes in operations and cumulative bytes.\n"
  },
  {
   "title": "Beacon State Reads (Bytes)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "store_beacon_state_read_bytes_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Beacon State Writes (Bytes)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "store_beacon_state_write_bytes_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Beacon State Reads (Ops)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "sci", "label": "Number of Ops" }
   ],
   "targets": [
    {
     "expr": "store_beacon_state_read_bytes_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Beacon State Writes (Ops)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "sci", "label": "Number of Ops" }
   ],
   "targets": [
    {
     "expr": "store_beacon_state_write_bytes_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 },
   "options": {
    "content": "\n### Beacon block read/write overhead\n\n\nThe encoding/decoding overheads of storing `BeaconBlock` (excluding action bytes read/write operations).\n"
   },
   "content": "\n### Beacon block read/write overhead\n\n\nThe encoding/decoding overheads of storing `BeaconBlock` (excluding action bytes read/write operations).\n"
  },
  {
   "title": "Beacon Block Read Overhead",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(store_beacon_block_read_overhead_seconds_sum{instance=\"$instance\"}[5m])\n/\nrate(store_beacon_block_read_overhead_seconds_count{instance=\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Beacon Block Write Overhead",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(store_beacon_block_write_overhead_seconds_sum{instance=\"$instance\"}[5m])\n/\nrate(store_beacon_block_write_overhead_seconds_count{instance=\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Beacon Block Reads (Bytes)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "store_beacon_block_read_bytes_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Beacon Block Writes (Bytes)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "store_beacon_block_write_bytes_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "options": {
    "content": "\n### BeaconBlock read/writes\n\n\nNumber of `BeaconBlock` read/writes in operations and cumulative bytes.\n"
   },
   "content": "\n### BeaconBlock read/writes\n\n\nNumber of `BeaconBlock` read/writes in operations and cumulative bytes.\n"
  },
  {
   "title": "Beacon Block Reads (Ops)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "sci", "label": "Number of Ops" }
   ],
   "targets": [
    {
     "expr": "store_beacon_block_read_bytes_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Beacon Block Writes (Ops)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 48 },
   "yaxes": [
    { "format": "sci", "label": "Number of Ops" }
   ],
   "targets": [
    {
     "expr": "store_beacon_block_write_bytes_total{instance=\"$instance\"}"
    }
   ]
  }
 ]
}