{
 "title": "Malloc Info",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(sync_eth2_synced{}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Snapshot Cache Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Snapshots" }
   ],
   "targets": [
    {
     "expr": "beacon_block_processing_snapshot_cache_size{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mallinfo_arena{instance=\"$instance\"} + mallinfo_hblkhd{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Non-mmap memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mallinfo_arena{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Mem-mapped bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mallinfo_hblkhd{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Mem-mapped blocks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mallinfo_hblks{instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Free blocks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mallinfo_ordblks{instance=\"$instance\"}",
     "legendFormat": "{{__name__}} {{instance}}"
    },
    {
     "expr": "mallinfo_smblks{instance=\"$instance\"}",
     "legendFormat": "{{__name__}} {{instance}}"
    }
   ]
  },
  {
   "title": "In-use memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mallinfo_uordblks{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Fastbin free memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mallinfo_fsmblks{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Free block memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mallinfo_fordblks{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Releasable heap top memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mallinfo_keepcost{instance=\"$instance\"}"
    }
   ]
  }
 ]
}