{
 "title": "Validator Client",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(sync_eth2_synced{}, instance)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "\n# Lighthouse Metrics\n\nMetrics collected from a Lighthouse Validator Client.\n\n\n\n"
   }
  },
  {
   "title": "Build",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lighthouse_info{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Local Beacon Block Proposers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "BeaconBlock" }
   ],
   "targets": [
    {
     "expr": "vc_beacon_block_proposer_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Local Attesters",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Attestation" }
   ],
   "targets": [
    {
     "expr": "vc_beacon_attester_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "options": {
    "content": "\n### Consensus\n\nOverview of consensus between nodes.\n\n\n"
   }
  },
  {
   "title": "Average Load (loadavg 1m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_loadavg_1{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "system_virt_mem_free_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Validator Client Resident Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 },
   "options": {
    "content": "\n### Consensus\n\nOverview of consensus between nodes.\n\n\n"
   }
  },
  {
   "title": "Distance from Genesis Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "dtdurations", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "vc_genesis_distance_seconds{instance=\"$instance\"} * -1"
    }
   ]
  },
  {
   "title": "Enabled Validators",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Validators" }
   ],
   "targets": [
    {
     "expr": "vc_validators_enabled_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Validators",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Validators" }
   ],
   "targets": [
    {
     "expr": "vc_validators_total_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 },
   "options": {
    "content": "\n### Consensus\n\nOverview of consensus between nodes.\n\n\n"
   }
  },
  {
   "title": "Block Signing Events",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none", "label": "BeaconBlock" }
   ],
   "targets": [
    {
     "expr": "vc_signed_beacon_blocks_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Attestation Signing Events",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "none", "label": "Attestation" }
   ],
   "targets": [
    {
     "expr": "vc_signed_attestations_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Aggregate Signing Events",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "none", "label": "SignedAggregateAndProof" }
   ],
   "targets": [
    {
     "expr": "vc_signed_aggregates_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Selection Proof Signing Events",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "none", "label": "SelectionProof" }
   ],
   "targets": [
    {
     "expr": "vc_signed_selection_proofs_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 30 },
   "options": {
    "content": "\n### Consensus\n\nOverview of consensus between nodes.\n\n\n"
   }
  },
  {
   "title": "Duties Service Times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(vc_duties_service_task_times_seconds_sum{instance=\"$instance\"}[30s])\n/\nrate(vc_duties_service_task_times_seconds_count{instance=\"$instance\"}[30s])"
    }
   ]
  },
  {
   "title": "Fork Service Times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(vc_fork_service_task_times_seconds_sum{instance=\"$instance\"}[30s])\n/\nrate(vc_fork_service_task_times_seconds_count{instance=\"$instance\"}[30s])"
    }
   ]
  },
  {
   "title": "Attestation Service Times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(vc_attestation_service_task_times_seconds_sum{instance=\"$instance\"}[30s])\n/\nrate(vc_attestation_service_task_times_seconds_count{instance=\"$instance\"}[30s])"
    }
   ]
  },
  {
   "title": "Block Service Times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(vc_beacon_block_service_task_times_seconds_sum{instance=\"$instance\"}[30s])\n/\nrate(vc_beacon_block_service_task_times_seconds_count{instance=\"$instance\"}[30s])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 37 },
   "options": {
    "content": "\n### Logs\n\nOverview of logs (includes beacon nodes)\n\n\n"
   }
  },
  {
   "title": "Info Logs per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(info_total{instance=\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Warn Logs per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(warn_total{instance=\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Error Logs per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(error_total{instance=\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Crit Logs Total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "crit_total{instance=\"$instance\"}"
    }
   ]
  }
 ]
}